version: '3'
services:
  craftycoffee.test:
    container_name: craftycoffee.test
    build:
      context: .
    restart: always
    #env_file: .env
    environment:
      - VIRTUAL_HOST=craftycoffee.test
    volumes:
      - .:/var/www
      - ./docker/sites/default.conf:/etc/nginx/sites-enabled/default
    networks:
      - pagevamp

networks:
  pagevamp:
    external: true
