enableVersioning: true
handle: aboutCraftyCoffee
name: 'About Crafty Coffee'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  706bd896-a738-4b80-a40a-19ef5e2ec936:
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 386d439b-e737-446a-8912-ff097e8990c5
type: structure
