field: 8bbd7ae6-eb99-4110-8cfa-4bbe8c227805 # Product Description
fieldLayouts:
  8a06bc56-099a-4a93-b112-3417598058e7:
    tabs:
      -
        elements:
          -
            fieldUid: 156a9889-c04c-499d-aa69-811eb94fcf25 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  156a9889-c04c-499d-aa69-811eb94fcf25: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: descriptionCopy
name: 'Description Copy'
sortOrder: 1
