bcc: null
cc: null
enabled: true
language: orderLanguage
name: 'Order Confirmation'
plainTextTemplatePath: ''
recipientType: customer
replyTo: s4jj4n@gmail.com
subject: 'Your Crafty Coffee Order'
templatePath: store/_emails/order-confirmation
to: null
