columnSuffix: null
contentColumnType: string
fieldGroup: 18e44013-6179-43b9-8ed4-f25056626fb3 # Store
handle: productImage
instructions: ''
name: 'Product Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:6a03726c-31cc-4cf7-9822-ecd15bd38d21' # Supplies
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a product image.'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:526be8f2-d24c-4d05-898e-c2f298e91236' # Drinks
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:6a03726c-31cc-4cf7-9822-ecd15bd38d21' # Supplies
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
