contentColumnType: text
fieldGroup: 3eaf4b14-aaab-4e2a-ae65-c058f65db41f
handle: styleDescription
instructions: ''
name: 'Style Description'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
